### ISSUE TITLE
is it possible to specify the rocker version you want to start from?

### ISSUE THREAD

**Issue by RMHogervorst** [ColinFay/dockerfiler#2]
I know rocker has versioned builds, but is it possible to specify that in dockerfiler?

**Comment by ColinFay** [comment]
Sure, you can choose your own when creating the `Dockerfile` object:

``` r
library(dockerfiler)
x <- Dockerfile$new(FROM = "rocker/r-ver:3.5.1")
x$RUN(r(install.packages('attempt')))
x
#> FROM rocker/r-ver:3.5.1
#> RUN R -e 'install.packages("attempt")'
```

<sup>Created on 2019-07-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by RMHogervorst** [comment]
Nice!
