### ISSUE TITLE
dock_from_desc() // dockerfiler VS golem

### ISSUE THREAD

**Issue by antoine-sachet** [ColinFay/dockerfiler#7]
Golem has a more advanced `dock_from_desc()` function. Shouldn't it live in `dockerfiler` rather than `golem`?

**Comment by ColinFay** [comment]
Hey, 

Yes, there's a plan on migrating everything from `{golem}` to here. 

For the backstory: `dock_from_desc()` was first born in `{dockerfiler}`, then it was copied and pasted to `{golem}` (as a temporary solution before `{dockerfiler}` was on CRAN), then it evolved in `{golem}` :)

But yeah, the idea is to migrate every docker related things to `{dockerfiler}`, see https://github.com/ThinkR-open/golem/issues/412

**Comment by statnmap** [comment]
If you want to be able to install dependencies listed in DESCRIPTION, but also their sub-dependencies, you can use a code like this:
```r
pkg_from_desc <- attachment::att_from_description()
the_sub_deps <- tools::package_dependencies(pkg_from_desc)
all_pkgs <- unique(c(pkg_from_desc, unlist(the_sub_deps)))
```

Indeed, this would also help dealing with dependencies in a {renv} context if you get all versions as well: https://github.com/ThinkR-open/golem/issues/282

**Comment by ColinFay** [comment]
`{golem}` now imports its dockerfile creation functions from `{dockerfiler}`
